# Generated by Django 6.0.1 on 2026-03-16 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('dependencia', models.CharField(blank=True, max_length=100, verbose_name='Dependencia')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Funcionario',
                'verbose_name_plural': 'Perfiles Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='VisitaRIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_local', models.CharField(max_length=64, unique=True, verbose_name='UUID local (app)')),
                ('nombre_establecimiento', models.CharField(max_length=255, verbose_name='Nombre del establecimiento')),
                ('nombre_propietario', models.CharField(blank=True, max_length=255, verbose_name='Nombre del propietario')),
                ('numero_documento', models.CharField(blank=True, max_length=30, verbose_name='Número de documento')),
                ('tipo_documento', models.CharField(blank=True, max_length=10, verbose_name='Tipo de documento')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección del establecimiento')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('actividad_economica', models.CharField(blank=True, max_length=10, verbose_name='Código actividad económica')),
                ('descripcion_actividad', models.CharField(blank=True, max_length=255, verbose_name='Descripción actividad')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('precision_gps', models.FloatField(blank=True, null=True, verbose_name='Precisión GPS (metros)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de sincronización'), ('sincronizado', 'Sincronizado')], default='pendiente', max_length=20)),
                ('fecha_visita', models.DateTimeField(verbose_name='Fecha y hora de la visita')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_rit', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Visita RIT',
                'verbose_name_plural': 'Visitas RIT',
                'ordering': ['-fecha_visita'],
            },
        ),
        migrations.CreateModel(
            name='FotoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='visitas_rit/%Y/%m/', verbose_name='Foto')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api_movil.visitarit', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Foto de visita',
                'verbose_name_plural': 'Fotos de visita',
                'ordering': ['orden'],
            },
        ),
    ]
