# Generated by Django 6.0.1 on 2026-04-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitarit',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Municipio'),
        ),
    ]
