# Generated by Django 6.0.1 on 2026-04-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0002_visitarit_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitarit',
            name='firma_contribuyente',
            field=models.TextField(blank=True, verbose_name='Firma contribuyente (base64)'),
        ),
        migrations.AddField(
            model_name='visitarit',
            name='firma_tipo',
            field=models.CharField(choices=[('DIBUJO', 'Firma dibujada'), ('OTP', 'Código OTP')], default='DIBUJO', max_length=10, verbose_name='Tipo de firma'),
        ),
    ]
