# Generated by Django 6.0.1 on 2026-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0003_visitarit_firma_contribuyente_visitarit_firma_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitarit',
            name='firma_funcionario',
            field=models.TextField(blank=True, verbose_name='Firma funcionario (base64)'),
        ),
    ]
