# Generated by Django 6.0.1 on 2026-04-28 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0004_visitarit_firma_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitarit',
            name='contribuyente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_como_contribuyente', to=settings.AUTH_USER_MODEL, verbose_name='Contribuyente'),
        ),
    ]
