# Generated by Django 6.0.1 on 2026-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0005_visitarit_contribuyente'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitarit',
            name='motivo_descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del motivo'),
        ),
        migrations.AddField(
            model_name='visitarit',
            name='motivo_no_atencion',
            field=models.CharField(blank=True, choices=[('CERRADO', 'Local cerrado'), ('AUSENTE', 'Propietario / encargado ausente'), ('NEGATIVA', 'Se negó a atender'), ('DIRECCION', 'Dirección no encontrada'), ('OTRO', 'Otro motivo')], max_length=20, verbose_name='Motivo de no atención'),
        ),
        migrations.AlterField(
            model_name='visitarit',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de sincronización'), ('sincronizado', 'Sincronizado'), ('no_atendida', 'No atendida')], default='pendiente', max_length=20),
        ),
    ]
