# Generated by Django 6.0.1 on 2026-04-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0006_visitarit_no_atendida'),
        ('tasks', '0037_auto_tipo_sancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitarit',
            name='registro_rit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visita_movil', to='tasks.registrorit', verbose_name='Registro RIT generado'),
        ),
    ]
