# Generated by Django 6.0.1 on 2026-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0007_visitarit_registro_rit_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitarit',
            name='estado',
            field=models.CharField(choices=[('precargada', 'Precargada (pendiente de visita)'), ('pendiente', 'Pendiente de sincronización'), ('sincronizado', 'Sincronizado'), ('no_atendida', 'No atendida')], default='pendiente', max_length=20),
        ),
    ]
