# Generated by Django 6.0.1 on 2026-01-18 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoRetencionICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tarifa', models.DecimalField(decimal_places=6, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracionICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_gravable', models.PositiveIntegerField()),
                ('opcion_uso', models.CharField(choices=[('INICIAL', 'Declaración inicial'), ('CORRECCION', 'Corrección')], default='INICIAL', max_length=20)),
                ('fecha_diligenciamiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], max_length=10)),
                ('tipo_juridica', models.CharField(blank=True, choices=[('SOCIEDAD', 'Sociedad'), ('CONSORCIO', 'Consorcio'), ('UNION_TEMPORAL', 'Unión temporal'), ('PATRIMONIO_AUTONOMO', 'Patrimonio autónomo'), ('OTRO', 'Otro')], max_length=30, null=True)),
                ('firma_declarante', models.ImageField(blank=True, null=True, upload_to='firmas/declarante/')),
                ('tiene_contador', models.BooleanField(default=False)),
                ('tiene_revisor_fiscal', models.BooleanField(default=False)),
                ('firma_contador', models.ImageField(blank=True, null=True, upload_to='firmas/contador/')),
                ('firma_revisor_fiscal', models.ImageField(blank=True, null=True, upload_to='firmas/revisor/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrige_a', models.ForeignKey(blank=True, help_text='Si es corrección, referencia a la declaración original o a la última versión.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='tasks.declaracionica')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.municipio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_gravados', models.BigIntegerField(default=0)),
                ('tarifa_aplicada', models.DecimalField(decimal_places=6, max_digits=10)),
                ('tipo_aplicado', models.CharField(max_length=15)),
                ('impuesto', models.BigIntegerField(default=0)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.actividadeconomica')),
                ('declaracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_actividades', to='tasks.declaracionica')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AccesoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=30)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetencionICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('tercero', models.CharField(max_length=200)),
                ('base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tarifa', models.DecimalField(decimal_places=6, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='declaracionica',
            constraint=models.UniqueConstraint(condition=models.Q(('opcion_uso', 'INICIAL')), fields=('user', 'municipio', 'anio_gravable'), name='uniq_ica_inicial_user_mpio_anio'),
        ),
        migrations.AlterUniqueTogether(
            name='accesoproceso',
            unique_together={('user', 'proceso')},
        ),
    ]
