# Generated by Django 6.0.1 on 2026-01-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionica',
            name='avisos_tableros',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='otro_tipo_juridica',
            field=models.CharField(blank=True, help_text='Solo aplica si Tipo jurídica = Otro.', max_length=100, null=True, verbose_name='Otro tipo jurídico'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='sobretasa_bomberil',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='total_a_pagar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='valor_ica',
            field=models.BigIntegerField(default=0),
        ),
    ]
