# Generated by Django 6.0.1 on 2026-01-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_created_task_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionica',
            name='clasificacion_contribuyente',
            field=models.CharField(blank=True, choices=[('REGIMEN_COMUN', 'Régimen común'), ('REGIMEN_SIMPLE', 'Régimen simple'), ('OTRA', 'Otra')], max_length=30, null=True, verbose_name='7. CLASIFICACIÓN CONTRIBUYENTE'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='5. CORREO ELECTRÓNICO'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='cual_documento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cuál (si tipo documento es OTRO)'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='departamento_notificacion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='3.2.DEPARTAMENTO'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='direccion_notificacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='3.DIRECCIÓN DE NOTIFICACIÓN'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='dv',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='municipio_notificacion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='3.1.MUNICIPIO O DISTRITO DE LA DIRECCIÓN DE NOTIFICACIÓN'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='nombre_razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1.NOMBRES Y APELLIDOS O RAZÓN SOCIAL'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=' No. DOCUMENTO'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='numero_establecimientos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='6.NÚMERO DE ESTABLECIMIENTOS'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='otra_clasificacion',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cuál (si clasificación es Otra)'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='4.TELÉFONO'),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('NIT', 'NIT'), ('OTRO', 'OTRO')], max_length=10, null=True, verbose_name='2.TIPO DE DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='anio_gravable',
            field=models.PositiveIntegerField(verbose_name='Año gravable'),
        ),
    ]
