# Generated by Django 6.0.1 on 2026-01-21 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('tasks', '0004_declaracionica_clasificacion_contribuyente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionica',
            name='departamento_notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaraciones_notificacion', to='catalogos.departamento'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='municipio_notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaraciones_notificacion', to='catalogos.municipio'),
        ),
    ]
