# Generated by Django 6.0.1 on 2026-01-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_declaracionica_departamento_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionica',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'CEDULA DE CIUDADANIA'), ('NIT', 'NIT'), ('PASAPORTE', 'PASAPORTE'), ('CE', 'CEDULA DE EXTRANJERIA'), ('OTRO', 'OTRO')], max_length=10, null=True, verbose_name='2.TIPO DE DOCUMENTO'),
        ),
    ]
