# Generated by Django 6.0.1 on 2026-01-21 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('tasks', '0006_alter_declaracionica_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionica',
            name='clasificacion_contribuyente',
            field=models.CharField(blank=True, choices=[('REGIMEN_COMUN', 'Régimen común'), ('REGIMEN_SIMPLE', 'Régimen simple'), ('OTRA', 'Otra')], max_length=30, null=True, verbose_name='7. Clasificación contribuyente'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='5. Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='cual_documento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cuál (si tipo de documento es OTRO)'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='departamento_notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaraciones_departamento_notificacion', to='catalogos.departamento'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='direccion_notificacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='3. Dirección de notificación'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='municipio_notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaraciones_municipio_notificacion', to='catalogos.municipio'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='nombre_razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1. Nombres y apellidos o razón social'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='No. documento'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='numero_establecimientos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='6. Número de establecimientos'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='4. Teléfono'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Cédula de extranjería'), ('OTRO', 'Otro')], max_length=10, null=True, verbose_name='2. Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], max_length=10, null=True),
        ),
    ]
