# Generated by Django 6.0.1 on 2026-01-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_declaracionica_clasificacion_contribuyente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionica',
            name='b11_menos_devoluciones_rebajas_descuentos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='b12_menos_exportaciones_venta_activos_fijos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='b13_menos_otras_actividades_excluidas_no_sujetas',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='b14_menos_actividades_exentas_por_acuerdo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='b8_total_ingresos_pais',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='b9_menos_ingresos_fuera_municipio',
            field=models.BigIntegerField(default=0),
        ),
    ]
