# Generated by Django 6.0.1 on 2026-01-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_declaracionica_b11_menos_devoluciones_rebajas_descuentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionica',
            name='capacidad_instalada_kw',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d22_sector_financiero',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d24_sobretasa_seguridad',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d26_exencion',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d27_retenciones',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d28_autorretenciones',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d29_anticipo_anterior',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d30_anticipo_siguiente',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d31_cual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d31_tipo_sancion',
            field=models.CharField(blank=True, choices=[('EXTEMPORANEIDAD', 'Extemporaneidad'), ('CORRECCION', 'Corrección'), ('INEXACTITUD', 'Inexactitud'), ('OTRA', 'Otra')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d31_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='d32_saldo_favor_anterior',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='es_generador_energia',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='imp_ley_56_1981',
            field=models.BigIntegerField(default=0),
        ),
    ]
