# Generated by Django 6.0.1 on 2026-01-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_declaracionica_capacidad_instalada_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionica',
            name='e36_descuento_pronto_pago',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='e37_intereses_mora',
            field=models.BigIntegerField(default=0),
        ),
    ]
