# Generated by Django 6.0.1 on 2026-01-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_declaracionica_e36_descuento_pronto_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionica',
            name='contador_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='contador_numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='contador_tarjeta_profesional',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='contador_tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'C.C.'), ('CE', 'C.E.'), ('TI', 'T.I.')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='revisor_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='revisor_numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='revisor_tarjeta_profesional',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='declaracionica',
            name='revisor_tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'C.C.'), ('CE', 'C.E.'), ('TI', 'T.I.')], max_length=3, null=True),
        ),
    ]
