# Generated by Django 5.1.6 on 2026-01-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('tasks', '0011_declaracionica_contador_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoproceso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='autoretencionica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='declaracionactividad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrorit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retencionica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PerfilContribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombres y apellidos o razón social')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Cédula de extranjería'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=30, verbose_name='Número de documento')),
                ('dv', models.CharField(blank=True, help_text='Solo aplica para NIT', max_length=2, null=True, verbose_name='DV')),
                ('cual_documento', models.CharField(blank=True, help_text='Solo aplica si tipo de documento es OTRO', max_length=60, null=True, verbose_name='Cuál documento')),
                ('direccion_notificacion', models.CharField(max_length=255, verbose_name='Dirección de notificación')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('numero_establecimientos', models.PositiveIntegerField(default=1, verbose_name='Número de establecimientos')),
                ('clasificacion_contribuyente', models.CharField(choices=[('REGIMEN_COMUN', 'Régimen común'), ('REGIMEN_SIMPLE', 'Régimen simple'), ('OTRA', 'Otra')], max_length=30, verbose_name='Clasificación contribuyente')),
                ('otra_clasificacion', models.CharField(blank=True, help_text='Solo aplica si clasificación es Otra', max_length=80, null=True, verbose_name='Otra clasificación')),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], max_length=10, verbose_name='Tipo de persona')),
                ('tipo_juridica', models.CharField(blank=True, choices=[('SOCIEDAD', 'Sociedad'), ('CONSORCIO', 'Consorcio'), ('UNION_TEMPORAL', 'Unión temporal'), ('PATRIMONIO_AUTONOMO', 'Patrimonio autónomo'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Tipo jurídica')),
                ('otro_tipo_juridica', models.CharField(blank=True, help_text='Solo aplica si tipo jurídica es Otro', max_length=100, null=True, verbose_name='Otro tipo jurídico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento_notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_contribuyente', to='catalogos.departamento', verbose_name='Departamento')),
                ('municipio_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_contribuyente', to='catalogos.municipio', verbose_name='Municipio de notificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Contribuyente',
                'verbose_name_plural': 'Perfiles de Contribuyentes',
            },
        ),
    ]
