# Generated by Django 5.1.6 on 2026-01-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('tasks', '0012_alter_accesoproceso_id_alter_autoretencionica_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrorit',
            options={'verbose_name': 'Registro RIT', 'verbose_name_plural': 'Registros RIT'},
        ),
        migrations.RemoveField(
            model_name='registrorit',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='registrorit',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registrorit',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='registrorit',
            name='razon_social',
        ),
        migrations.AddField(
            model_name='registrorit',
            name='clasificacion_contribuyente',
            field=models.CharField(choices=[('REGIMEN_COMUN', 'Régimen común'), ('REGIMEN_SIMPLE', 'Régimen simple'), ('OTRA', 'Otra')], default='REGIMEN_COMUN', max_length=30, verbose_name='Clasificación contribuyente'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='correo_electronico',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='cual_documento',
            field=models.CharField(blank=True, help_text='Solo aplica si tipo de documento es OTRO', max_length=60, null=True, verbose_name='Cuál documento'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='departamento_notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_rit', to='catalogos.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='direccion_notificacion',
            field=models.CharField(default='', max_length=255, verbose_name='Dirección de notificación'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='dv',
            field=models.CharField(blank=True, help_text='Solo aplica para NIT', max_length=2, null=True, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='municipio_notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_rit', to='catalogos.municipio', verbose_name='Municipio de notificación'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='nombre_razon_social',
            field=models.CharField(default='', max_length=255, verbose_name='Nombres y apellidos o razón social'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='numero_documento',
            field=models.CharField(default='', max_length=30, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='numero_establecimientos',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de establecimientos'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='otra_clasificacion',
            field=models.CharField(blank=True, help_text='Solo aplica si clasificación es Otra', max_length=80, null=True, verbose_name='Otra clasificación'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='otro_tipo_juridica',
            field=models.CharField(blank=True, help_text='Solo aplica si tipo jurídica es Otro', max_length=100, null=True, verbose_name='Otro tipo jurídico'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='telefono',
            field=models.CharField(default='', max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Cédula de extranjería'), ('OTRO', 'Otro')], default='CC', max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='tipo_juridica',
            field=models.CharField(blank=True, choices=[('SOCIEDAD', 'Sociedad'), ('CONSORCIO', 'Consorcio'), ('UNION_TEMPORAL', 'Unión temporal'), ('PATRIMONIO_AUTONOMO', 'Patrimonio autónomo'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Tipo jurídica'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='tipo_persona',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], default='NATURAL', max_length=10, verbose_name='Tipo de persona'),
        ),
    ]
