# Generated by Django 6.0.1 on 2026-01-22 22:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('tasks', '0013_alter_registrorit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorit',
            name='clase_contribuyente',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('INFORMAL_OCASIONAL', 'Informal/Ocasional'), ('REGIMEN_SIMPLE', 'Régimen Simple')], default='NORMAL', max_length=20, verbose_name='Clase de contribuyente'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='es_autorretenedor_ica',
            field=models.BooleanField(default=False, verbose_name='Autorretenedor ICA'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='es_retenedor_ica',
            field=models.BooleanField(default=False, verbose_name='Retenedor ICA'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='fecha_recepcion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de recepción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrorit',
            name='firma_contribuyente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/rit/contribuyente/', verbose_name='Firma del contribuyente o representante legal'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='firma_contribuyente_documento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Documento del firmante'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='firma_contribuyente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del firmante'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='firma_funcionario',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/rit/funcionario/', verbose_name='Firma del funcionario'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='firma_funcionario_documento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Documento del funcionario'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='firma_funcionario_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del funcionario'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('TRASPASO', 'Traspaso (venta, fusión, herencia)'), ('TERMINACION', 'Terminación del negocio')], max_length=15, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='opcion_uso',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripción'), ('ACTUALIZACION', 'Actualización'), ('CANCELACION', 'Cancelación')], default='INSCRIPCION', max_length=15, verbose_name='Opción de uso'),
        ),
        migrations.AddField(
            model_name='registrorit',
            name='tipo_cancelacion',
            field=models.CharField(blank=True, choices=[('TOTAL', 'Total (queda sin establecimientos activos)'), ('PARCIAL', 'Parcial (queda con establecimientos activos)')], max_length=10, null=True, verbose_name='Tipo de cancelación'),
        ),
        migrations.AlterField(
            model_name='accesoproceso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='autoretencionica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='declaracionactividad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilcontribuyente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrorit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retencionica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ActividadEconomicaRIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_gravable_mensual', models.BigIntegerField(default=0, verbose_name='Base gravable mensual')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.actividadeconomica', verbose_name='Actividad económica')),
                ('rit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_rit', to='tasks.registrorit')),
            ],
            options={
                'verbose_name': 'Actividad Económica RIT',
                'verbose_name_plural': 'Actividades Económicas RIT',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EstablecimientoRIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del establecimiento')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('fecha_inicio_actividades', models.DateField(verbose_name='Fecha de inicio de actividades')),
                ('tiene_avisos_tableros', models.BooleanField(default=False, verbose_name='¿Tiene avisos y tableros?')),
                ('fecha_cancelacion', models.DateField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('rit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='tasks.registrorit')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegalRIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PASAPORTE', 'Pasaporte'), ('NIT', 'NIT')], max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=30, verbose_name='Número de documento')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('rit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='tasks.registrorit')),
            ],
            options={
                'verbose_name': 'Representante Legal',
                'verbose_name_plural': 'Representantes Legales',
                'ordering': ['orden'],
            },
        ),
    ]
