# Generated by Django 6.0.1 on 2026-01-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_registrorit_clase_contribuyente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorit',
            name='radicado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de radicado'),
        ),
        migrations.AddField(
            model_name='representantelegalrit',
            name='tipo_representante',
            field=models.CharField(choices=[('REPRESENTANTE_LEGAL', 'Representante Legal'), ('SOCIO_SOLIDARIO', 'Socio Solidario')], default='REPRESENTANTE_LEGAL', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='representantelegalrit',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
