# Generated by Django 5.1.6 on 2026-01-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_add_estado_to_rit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=100, verbose_name='Nombre de configuración')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('logo_izquierdo', models.ImageField(blank=True, help_text='Tamaño recomendado: 150x150px', null=True, upload_to='config/logos/', verbose_name='Logo izquierdo (Escudo/Alcaldía)')),
                ('logo_derecho', models.ImageField(blank=True, help_text='Tamaño recomendado: 150x150px', null=True, upload_to='config/logos/', verbose_name='Logo derecho (Institucional)')),
                ('nombre_entidad', models.CharField(default='Secretaría de Hacienda', max_length=200, verbose_name='Nombre de la entidad')),
                ('nombre_municipio', models.CharField(default='Municipio de Segovia', max_length=100, verbose_name='Nombre del municipio')),
                ('slogan', models.CharField(blank=True, default='Portal de Servicios Tributarios', max_length=200, null=True, verbose_name='Slogan o subtítulo')),
                ('color_primario', models.CharField(default='#1a5276', help_text='Formato hexadecimal, ej: #1a5276', max_length=7, verbose_name='Color primario')),
                ('color_secundario', models.CharField(default='#2c3e50', help_text='Formato hexadecimal, ej: #2c3e50', max_length=7, verbose_name='Color secundario')),
                ('color_radicado', models.CharField(default='#c0392b', help_text='Formato hexadecimal, ej: #c0392b', max_length=7, verbose_name='Color del radicado')),
                ('color_exito', models.CharField(default='#27ae60', help_text='Formato hexadecimal, ej: #27ae60', max_length=7, verbose_name='Color de éxito/total')),
                ('mostrar_instructivo', models.BooleanField(default=True, verbose_name='Mostrar instructivo en PDF')),
                ('texto_instructivo', models.TextField(default='1. Conserve este documento como soporte de su trámite tributario.\n2. El número de radicado es su comprobante oficial ante la administración municipal.\n3. Para cualquier consulta, presente este documento con el número de radicado.\n4. Este documento fue generado electrónicamente y es válido sin firma.', help_text='Cada línea será un punto del instructivo', verbose_name='Texto del instructivo')),
                ('texto_pie_pagina', models.CharField(blank=True, default='Documento generado por el Portal de Servicios Tributarios', max_length=300, null=True, verbose_name='Texto adicional pie de página')),
                ('direccion_entidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de la entidad')),
                ('telefono_entidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de la entidad')),
                ('email_entidad', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la entidad')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de PDF',
                'verbose_name_plural': 'Configuraciones de PDF',
            },
        ),
    ]
