# Generated by Django 6.0.1 on 2026-02-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_accesoproceso_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorit',
            name='tiene_establecimientos',
            field=models.BooleanField(default=True, verbose_name='¿Tiene establecimientos?'),
        ),
    ]
