# Generated by Django 6.0.1 on 2026-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_add_must_change_password_to_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionica',
            name='d31_tipo_sancion',
            field=models.CharField(blank=True, choices=[('NINGUNA', 'Ninguna'), ('EXTEMPORANEIDAD', 'Extemporaneidad'), ('CORRECCION', 'Corrección'), ('INEXACTITUD', 'Inexactitud'), ('OTRA', 'Otra')], max_length=20, null=True),
        ),
    ]
