# Generated by Django 6.0.1 on 2026-03-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_declaracionica_d31_tipo_sancion'),
        ('tasks', '0026_firma_otp_ica'),
    ]

    operations = [
    ]
