# Generated by Django 6.0.1 on 2026-03-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_firma_otp_contador_revisor'),
        ('tasks', '0027_merge_20260309_0208'),
    ]

    operations = [
    ]
