# Generated by Django 6.0.1 on 2026-03-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_firma_otp_contador_revisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionica',
            name='clasificacion_contribuyente',
            field=models.CharField(blank=True, choices=[('REGIMEN_COMUN', 'Régimen común de ICA'), ('REGIMEN_SIMPLE', 'Régimen simplificado'), ('OTRA', 'Otra')], max_length=30, null=True, verbose_name='7. Clasificación contribuyente'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='d31_tipo_sancion',
            field=models.CharField(blank=True, choices=[('NINGUNA', 'Ninguna'), ('EXTEMPORANEIDAD', 'Extemporaneidad'), ('CORRECCION', 'Corrección'), ('INEXACTITUD', 'Inexactitud'), ('OTRA', 'Otra')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilcontribuyente',
            name='clasificacion_contribuyente',
            field=models.CharField(choices=[('REGIMEN_COMUN', 'Régimen común de ICA'), ('REGIMEN_SIMPLE', 'Régimen simplificado'), ('OTRA', 'Otra')], max_length=30, verbose_name='Clasificación contribuyente'),
        ),
        migrations.AlterField(
            model_name='registrorit',
            name='clasificacion_contribuyente',
            field=models.CharField(choices=[('REGIMEN_COMUN', 'Régimen común de ICA'), ('REGIMEN_SIMPLE', 'Régimen simplificado'), ('OTRA', 'Otra')], default='REGIMEN_COMUN', max_length=30, verbose_name='Clasificación contribuyente'),
        ),
    ]
