# Generated by Django 6.0.1 on 2026-03-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_declaracionica_clasificacion_contribuyente_and_more'),
    ]

    operations = [
    ]
