# Generated by Django 6.0.1 on 2026-03-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_merge_20260310_0247'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='declaracionica',
            name='uniq_ica_inicial_user_mpio_anio',
        ),
    ]
