# Generated by Django 6.0.1 on 2026-03-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_merge_20260309_0239'),
        ('tasks', '0030_remove_uniq_ica_inicial_constraint'),
    ]

    operations = [
    ]
