# Generated by Django 5.1.6 on 2026-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_ica_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoproceso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='actividadeconomicarit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='autoretencionica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracionpdf',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracionpdf',
            name='instructivo_ica_col_derecha',
            field=models.TextField(default='### C. DISCRIMINACIÓN DE ACTIVIDADES GRAVADAS\n\nSegún las actividades que realice como PERSONA NATURAL o JURÍDICA en Segovia, registre para cada una la información requerida, iniciando con la actividad principal.\n\nConsulte el código y tarifa de cada actividad en el Estatuto Tributario Municipal vigente de Segovia.\n\nEscriba en la columna "IMPUESTO" el valor que resulte de multiplicar los ingresos gravados por la tarifa. Ejemplo: $10.000.000 x 8 ÷ 1000 = $80.000.\n\n## TOTAL INGRESOS GRAVADOS\nTotalice la sumatoria de la columna "Ingresos Gravados".\n\n## 17. TOTAL IMPUESTO\nTotalice la sumatoria de la columna "IMPUESTO".\n\n## 18. LIQUIDACIÓN – LEY 56 DE 1981\nSólo lo diligencian empresas generadoras de energía eléctrica (Art. 51, Ley 383 de 1997). Escriba en kilovatios la capacidad instalada de la generadora en el municipio.\n\n### D. LIQUIDACIÓN PRIVADA\n\n## 20. TOTAL IMPUESTO DE INDUSTRIA Y COMERCIO (RENGLÓN 17 + 19)\nEscriba el impuesto del renglón N° 17 más el valor de la casilla N° 19.\n\n## 21. IMPUESTO DE AVISOS Y TABLEROS (15% del renglón 20)\nSi tiene avisos y tableros en Segovia, multiplique el renglón N° 20 por el 15%.\n\n## 22. PAGO POR UNIDADES COMERCIALES ADICIONALES DEL SECTOR FINANCIERO\nLiquidar 25 UVT por cada oficina adicional excepto la principal (Establecimientos de crédito, instituciones financieras y compañías de seguros).\n\n## 23. SOBRETASA BOMBERIL\nNo aplica para el Municipio de Segovia.\n\n## 24. SOBRETASA DE SEGURIDAD\nNo aplica para el Municipio de Segovia.\n\n## 25. TOTAL IMPUESTO A CARGO\nResultado de sumar los renglones 20 + 21 + 22 + 23 + 24.\n\n## 26. MENOS EXENCIÓN O EXONERACIÓN SOBRE EL IMPUESTO\nSi tiene derecho a disminuir el impuesto liquidado por una exención concedida, escriba el valor exento.\n\n## 27. MENOS RETENCIONES\nValor retenido el año anterior a favor del Municipio de Segovia, anexando los certificados de retención.\n\n## 28. MENOS AUTORRETENCIONES\nNo aplica para el Municipio de Segovia.\n\n## 29. MENOS ANTICIPO LIQUIDADO EN EL AÑO ANTERIOR\nSólo aplica a contribuyentes nuevos inscritos en el R.I.T. en el año inmediatamente anterior.\n\n## 30. ANTICIPO PARA EL AÑO SIGUIENTE\nNo aplica para el Municipio de Segovia.\n\n## 31. SANCIONES\nValor de sanciones tributarias a liquidar con esta declaración (Arts. 192 a 198 del Estatuto Tributario Municipal).\n\n## 32. MENOS SALDO A FAVOR DEL PERIODO ANTERIOR\nEscriba el saldo a favor con los anexos que acrediten su determinación.\n\n## 33. TOTAL SALDO A CARGO\nResultado: renglón 25 - 26 - 27 - 28 - 29 + 30 + 31 - 32.\n\n## 34. TOTAL SALDO A FAVOR\nSi el resultado del renglón 25 - 26 - 27 - 28 - 29 + 30 + 31 - 32 es menor a cero.\n\n### E. PAGO\n\n## 35. VALOR A PAGAR\nEscriba el valor que va a pagar durante la vigencia fiscal declarada. Si no va a pagar, escriba cero.\n\n## 36. DESCUENTO POR PRONTO PAGO\nNo aplica para la declaración privada de Segovia.\n\n## 37. INTERESES DE MORA\nNo aplica para la declaración privada de Segovia.\n\n## 38. TOTAL A PAGAR\nEscriba el resultado del renglón N° 35.\n\n### SELECCIÓN PAGO VOLUNTARIO\n\nEste recuadro no aplica para la Declaración que se presenta en el Municipio de Segovia (Antioquia).\n\n### F. FIRMAS\n\n## FIRMA DEL DECLARANTE\nEsta declaración debe ser firmada por quien deba cumplir el deber formal de declarar.\n\n## FIRMA DEL CONTADOR O REVISOR FISCAL\nDiligencie si existe la obligación ante el Municipio de Segovia.', help_text='Use ### ETIQUETA para iniciar una sección con franja vertical. Use ## TÍTULO para encabezados en negrita. Separe bloques con línea en blanco.', verbose_name='Instructivo ICA – columna derecha'),
        ),
        migrations.AlterField(
            model_name='configuracionpdf',
            name='instructivo_ica_col_izquierda',
            field=models.TextField(default='Este formulario lo deben utilizar las personas naturales y jurídicas que ejerzan directa o indirectamente actividades permanentes u ocasionales en la jurisdicción del Municipio de Segovia, Antioquia, en cumplimiento de la Ley 14 de 1983, Decreto Ley 1333 de 1986 y el Acuerdo Municipal vigente.\n\nEl formulario debe ser presentado ante el Área Administrativa de Impuestos de la Alcaldía Municipal de Segovia, Segovia, Antioquia, en las fechas del Calendario Tributario.\n\nTodas las casillas de valores deben aproximarse al múltiplo de mil (1000) más cercano. Si no hay valor, escriba cero (0).\n\n## MUNICIPIO O DISTRITO\nEscriba SEGOVIA, municipio ante quien presenta esta declaración.\n\n## DEPARTAMENTO\nEscriba ANTIOQUIA.\n\n## FECHA MÁXIMA DE PRESENTACIÓN\nConsulte el decreto municipal con el Calendario Tributario del Municipio de Segovia.\n\n## AÑO GRAVABLE\nEl período gravable es el año calendario inmediatamente anterior al de presentación.\n\n## DECLARACIÓN INICIAL\nMarque si es la primera declaración por este período gravable.\n\n## CORRECCIÓN\nSi corrige una declaración anterior, escriba el número, día, mes y año de la declaración que corrige.\n\n### A. INFORMACIÓN DEL CONTRIBUYENTE\n\n## 1. NOMBRES Y APELLIDOS O RAZÓN SOCIAL\nEscriba los datos tal como figuran en el documento de identificación, R.U.T. o certificado de Cámara de Comercio. Si es PERSONA NATURAL, escriba nombres y apellidos completos. Si es PERSONA JURÍDICA, escriba la razón social completa.\n\n## 2. TIPO DE DOCUMENTO\nMarque con "X" el recuadro y escriba el número de C.C., Nit. o Tarjeta de Identidad. Para el NIT, el dígito de verificación va separado con guion.\n\n## 3. DIRECCIÓN DE NOTIFICACIÓN\nEscriba la dirección que usa para efectos tributarios, indicando municipio y departamento. – Dirección establecimiento: escriba la dirección de establecimientos, agencias o sucursales en Segovia.\n\n## 4. TELÉFONO\nEscriba el número de teléfono de contacto.\n\n## 5. CORREO ELECTRÓNICO\nEscriba la dirección electrónica de contacto.\n\n## 6. NÚMERO DE ESTABLECIMIENTOS\nEscriba el número de establecimientos comerciales, agencias, oficinas o sucursales ubicadas en Segovia.\n\n## 7. CLASIFICACIÓN\nEscriba si es Gran Contribuyente, Régimen Común o Simplificado según la DIAN. – Tipo de actividad económica: marque si desarrolla en Segovia una actividad en forma permanente u ocasional.\n\n### B. BASE GRAVABLE\n\n## 8. TOTAL INGRESOS ORDINARIOS Y EXTRAORDINARIOS DEL PERÍODO EN TODO EL PAÍS\nRegistre la totalidad de ingresos obtenidos en todo el país durante el período gravable, incluyendo rendimientos financieros y comisiones.\n\n## 9. MENOS INGRESOS FUERA DE ESTE MUNICIPIO\nRegistre el total de ingresos obtenidos fuera del municipio de Segovia.\n\n## 10. TOTAL INGRESOS EN ESTE MUNICIPIO (RENGLÓN 8 MENOS 9)\nResultado de restar los ingresos fuera del municipio al total del país.\n\n## 11. MENOS DEVOLUCIONES, REBAJAS Y DESCUENTOS\nValor de ingresos por devoluciones, rebajas o descuentos registrados en Segovia del año anterior.\n\n## 12. MENOS INGRESOS POR EXPORTACIONES\nValor de exportaciones realizadas en el año inmediatamente anterior.\n\n## 13. MENOS VENTA DE ACTIVOS FIJOS\nValor de venta de activos fijos en el año inmediatamente anterior.\n\n## 14. MENOS ACTIVIDADES EXCLUIDAS, NO SUJETAS Y OTROS INGRESOS NO GRAVADOS\nValor de ingresos por actividades excluidas, no sujetas u otros no gravados según las normas del impuesto de industria y comercio.\n\n## 15. MENOS ACTIVIDADES EXENTAS EN ESTE MUNICIPIO\nValor de ingresos de actividades con tratamiento de exención concedido por el Concejo Municipal de Segovia.\n\n## 16. TOTAL INGRESOS GRAVABLES (RENGLÓN 10 MENOS 11, 12, 13, 14 Y 15)\nResultado de restar al total de ingresos en el municipio los conceptos deducibles de los renglones 11 a 15.', help_text='Use ### ETIQUETA para iniciar una sección con franja vertical. Use ## TÍTULO para encabezados en negrita. Separe bloques con línea en blanco. El texto antes del primer ### se muestra como introducción sin franja.', verbose_name='Instructivo ICA – columna izquierda'),
        ),
        migrations.AlterField(
            model_name='declaracionactividad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='declaracionica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='establecimientorit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='firmaotpica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='firmaotprit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilcontribuyente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrorit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='representantelegalrit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retencionica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='CodigoEstablecimiento',
        ),
    ]
