# Generated by Django 6.0.1 on 2026-04-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_update_clase_contribuyente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorit',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_FIRMA', 'Pendiente de firma'), ('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_FIRMA', max_length=16, verbose_name='Estado del RIT'),
        ),
    ]
