# Generated by Django 6.0.4 on 2026-05-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('tasks', '0039_rit_estado_pendiente_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcontribuyente',
            name='municipio_notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_contribuyente', to='catalogos.municipio', verbose_name='Municipio de notificación'),
        ),
    ]
