"""
Django settings for djangocrud project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables de entorno desde .env (solo en desarrollo local)
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-tk%t0rzlmp4k^vf(iclcuv8j796g8wp1gej8rrk)if&5b0dcw)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'salgar.portalterritorial.com.co',
    'www.salgar.portalterritorial.com.co',
    '127.0.0.1',
    'localhost',
    '10.0.2.2',       # Emulador Android
    '192.168.40.55',  # PC local (dispositivos físicos en la misma red)
    '192.168.1.184',  # PC local red actual
]

CSRF_TRUSTED_ORIGINS = [
    'https://salgar.portalterritorial.com.co',
    'https://www.salgar.portalterritorial.com.co',
]

# Permitir previsualización de PDFs en iframes del mismo dominio
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
    'import_export',
    'catalogos.apps.CatalogosConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'api_movil',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangocrud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangocrud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

LOGIN_URL = '/signin/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Configuración de mensajes para Bootstrap
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# EmailJS (todos los correos del sistema usan EmailJS REST API)
EMAILJS_SERVICE_ID           = os.environ.get('EMAILJS_SERVICE_ID',           'service_ei3i1qv')
EMAILJS_PUBLIC_KEY           = os.environ.get('EMAILJS_PUBLIC_KEY',           'esiipR7u2nzRWebYA')
EMAILJS_PRIVATE_KEY          = os.environ.get('EMAILJS_PRIVATE_KEY',          '3ysOa6y2essWXF_HN7KjU')
EMAILJS_TEMPLATE_RESET       = os.environ.get('EMAILJS_TEMPLATE_RESET',       'template_p4plyvh')
EMAILJS_TEMPLATE_OTP         = os.environ.get('EMAILJS_TEMPLATE_OTP',         'template_1a6j14l')
EMAILJS_TEMPLATE_CREDENCIALES = os.environ.get('EMAILJS_TEMPLATE_CREDENCIALES', 'template_9e2s5zl')
# En DEBUG (local) deshabilitar verificación SSL automáticamente (antivirus intercepta HTTPS)
# En producción siempre True. Se puede forzar con env var EMAILJS_VERIFY_SSL=true/false
_ssl_default = 'false' if DEBUG else 'true'
EMAILJS_VERIFY_SSL           = os.environ.get('EMAILJS_VERIFY_SSL', _ssl_default).lower() != 'false'

# Django mail backend desactivado (no se usa SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

# ========================
# DJANGO REST FRAMEWORK
# ========================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS':  True,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '%(levelname)s %(asctime)s %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'tasks.emailjs': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}